### ISSUE TITLE
Not working for me

### ISSUE THREAD

**Issue by ASchneiderBR** [kounoike/obs-virtualbg#31]
Hello @kounoike, thanks for taking the time to create this tool :)

Not sure what I'm doing wrong: after adding on both video effects and filters, my webcam image simple goes blank, 100% transparent.

![image](https://user-images.githubusercontent.com/25224882/136106005-7c1b2282-99d5-485f-a44a-94a9fd57f68a.png)

I'm trying to use it on a webcam source, 720p30.

Also, I love the idea of using this kind of plugin but since you are using this effect on two different places of the same source, this makes unusable on other kind of sources, like a browser source. I was looking for a solution like this one to use with VDO.Ninja but it seems that would not be possible, since it doesn't have the video effects part, inside filters:

![image](https://user-images.githubusercontent.com/25224882/136106439-2cb5b077-366c-4087-9521-bd98d8f2ca66.png)

Do you think that would be possible someday?

Thanks!

**Comment by kounoike** [comment]
@ASchneiderBR sorry, forgotten mention

**Comment by ASchneiderBR** [comment]
Hey there!

Here's a log file. When I enable the first filter, it starts spamming my log with the error `device_texture_create (D3D11): Failed to create 2D texture (80070057)`, then after the second one is turned on, OBS crashes now...

[2021-10-06 13-44-24.txt](https://github.com/kounoike/obs-virtualbg/files/7295787/2021-10-06.13-44-24.txt)

Too bad this plugin would be usable by a browser source, that would be the main feature for me :)

Thanks a lot!
