### ISSUE TITLE
Crashes OBS Everytime

### ISSUE THREAD

**Issue by brucerothwell** [kounoike/obs-virtualbg#36]
Crash and Log files attached.

[Crash 2021-10-07 09-45-33.txt](https://github.com/kounoike/obs-virtualbg/files/7304738/Crash.2021-10-07.09-45-33.txt)
[2021-10-07 09-44-24.txt](https://github.com/kounoike/obs-virtualbg/files/7304739/2021-10-07.09-44-24.txt)

**Comment by dosoft** [comment]
crashed as soon as I add audio/video filter.

**Comment by P-Gaz** [comment]
Hi, i have the same problem all the time i add "Visual Backgroud detector" OBS crash, this is the LOG :
[Crash 2022-01-20 20-28-56.txt](https://github.com/kounoike/obs-virtualbg/files/7907994/Crash.2022-01-20.20-28-56.txt).

**Comment by kounoike** [comment]
@P-Gaz Please add obs log, not only crash log.

**Comment by TidusWulf** [comment]
having a crash as well when I add the detector.
[Crash 2022-07-25 09-46-27.txt](https://github.com/kounoike/obs-virtualbg/files/9184350/Crash.2022-07-25.09-46-27.txt)
[2022-07-25 09-46-11.txt](https://github.com/kounoike/obs-virtualbg/files/9184353/2022-07-25.09-46-11.txt)
