### ISSUE TITLE
Gray screen.

### ISSUE THREAD

**Issue by Nemnon** [kounoike/obs-virtualbg#48]
![Screenshot_1](https://user-images.githubusercontent.com/48986119/146644100-df12c911-eb1d-4f43-bd46-75693870aa3f.png)

17:11:06.396: CPU Name: AMD Ryzen 7 2700 Eight-Core Processor          
17:11:06.396: CPU Speed: 3200MHz
17:11:06.396: Physical Cores: 8, Logical Cores: 16
17:11:06.396: Physical Memory: 32689MB Total, 16340MB Free
17:11:06.396: Windows Version: 10.0 Build 22000 (release: 2009; revision: 376; 64-bit)
17:11:06.396: Running as administrator: false
17:11:06.397: Aero is Enabled (Aero is always on for windows 8 and above)
17:11:06.397: Windows 10 Gaming Features:
17:11:06.397: 	Game DVR: On
17:11:06.397: 	Game Mode: Off
17:11:06.397: Sec. Software Status:
17:11:06.399: 
17:11:06.399: 
17:11:06.399: Current Date/Time: 2021-12-18, 17:11:06
17:11:06.399: Browser Hardware Acceleration: true
17:11:06.399: Portable mode: false
17:11:06.679: OBS 27.1.3 (64-bit, windows)
17:11:06.679: ---------------------------------
17:11:06.687: ---------------------------------
17:11:06.687: audio settings reset:
17:11:06.687: 	samples per sec: 48000
17:11:06.687: 	speakers:        2
17:11:06.691: ---------------------------------
17:11:06.691: Initializing D3D11...
17:11:06.691: Available Video Adapters: 
17:11:06.694: 	Adapter 0: Radeon RX 580 Series
17:11:06.694: 	  Dedicated VRAM: 4273434624
17:11:06.694: 	  Shared VRAM:    4253929472
17:11:06.694: 	  PCI ID:         1002:67df
17:11:06.694: 	  Driver Version: 30.0.13033.1000
17:11:06.694: 	  output 0: pos={0, 0}, size={1920, 1200}, attached=true, refresh=60, name=DELL U2412M
17:11:06.694: 	  output 1: pos={1920, 0}, size={1920, 1080}, attached=true, refresh=59, name=SAMSUNG
17:11:06.696: Loading up D3D11 on adapter Radeon RX 580 Series (0)
17:11:06.740: D3D11 loaded successfully, feature level used: b000
17:11:06.740: DXGI increase maximum frame latency success
17:11:06.740: D3D11 GPU priority setup failed (not admin?)
17:11:07.262: ---------------------------------
17:11:07.262: video settings reset:
17:11:07.262: 	base resolution:   1920x1080
17:11:07.262: 	output resolution: 1280x720
17:11:07.262: 	downscale filter:  Bicubic
17:11:07.262: 	fps:               30/1
17:11:07.262: 	format:            NV12
17:11:07.262: 	YUV mode:          709/Partial
17:11:07.262: NV12 texture support enabled
17:11:07.263: Audio monitoring device:
17:11:07.263: 	name: CABLE-A Input (VB-Audio Cable A)
17:11:07.263: 	id: {0.0.0.00000000}.{3b6747bb-d74a-4b79-a513-d5096e331989}
17:11:07.263: ---------------------------------
17:11:07.264: Skipping module '../../obs-plugins/64bit/chrome_elf.dll', not an OBS plugin
17:11:07.268: [CoreAudio encoder]: CoreAudio AAC encoder not installed on the system or couldn't be loaded
17:11:07.269: Failed to load 'en-US' text for module: 'decklink-captions.dll'
17:11:07.269: Failed to load 'en-US' text for module: 'decklink-ouput-ui.dll'
17:11:07.270: Skipping module '../../obs-plugins/64bit/DirectML.dll', not an OBS plugin
17:11:07.526: [AMF] Version 2.7.0 loaded (Compiled: 1.4.14.0, Runtime: 1.4.22.0, Library: 1;4;22;0;21.30.25.05;202110051216;CL#2364427).
17:11:07.565: [AMF] <Id: 1> Unable to set converter transfer characteristic, error AMF_NOT_FOUND (code 11)
17:11:07.616: [AMF] <Id: 2> Unable to set converter transfer characteristic, error AMF_NOT_FOUND (code 11)
17:11:07.629: [AMF] [Capability Manager] Testing Direct3D 11 Adapter 'Radeon RX 580 Series (VEN_1002/DEV_67df/SUB_e3531da2/REV_00e7)':
17:11:07.629:   H264/AVC: Supported
17:11:07.629:   H265/HEVC: Supported
17:11:07.629: 
17:11:07.640: Skipping module '../../obs-plugins/64bit/libcef.dll', not an OBS plugin
17:11:07.650: Skipping module '../../obs-plugins/64bit/libEGL.dll', not an OBS plugin
17:11:07.650: Skipping module '../../obs-plugins/64bit/libGLESv2.dll', not an OBS plugin
17:11:07.658: [obs-browser]: Version 2.16.3
17:11:07.658: [obs-browser]: CEF Version 75.1.16+g16a67c4+chromium-75.0.3770.100
17:11:07.665: [noise suppress]: NVIDIA RTX denoiser disabled, redistributable not found
17:11:08.332: Failed to load 'ru-RU' text for module: 'obs-virtualbg.dll'
17:11:08.336: Skipping module '../../obs-plugins/64bit/onnxruntime.dll', not an OBS plugin
17:11:08.343: Couldn't find VLC installation, VLC video source disabled
17:11:08.352: A DeckLink iterator could not be created.  The DeckLink drivers may not be installed
17:11:08.353: No blackmagic support
17:11:08.361: ---------------------------------
17:11:08.361:   Loaded Modules:
17:11:08.361:     win-wasapi.dll
17:11:08.361:     win-mf.dll
17:11:08.361:     win-dshow.dll
17:11:08.361:     win-decklink.dll
17:11:08.361:     win-capture.dll
17:11:08.361:     vlc-video.dll
17:11:08.361:     text-freetype2.dll
17:11:08.361:     rtmp-services.dll
17:11:08.361:     obs-x264.dll
17:11:08.361:     obs-vst.dll
17:11:08.361:     obs-virtualbg.dll
17:11:08.361:     obs-transitions.dll
17:11:08.361:     obs-text.dll
17:11:08.361:     obs-qsv11.dll
17:11:08.361:     obs-outputs.dll
17:11:08.361:     obs-filters.dll
17:11:08.361:     obs-ffmpeg.dll
17:11:08.361:     obs-browser.dll
17:11:08.361:     image-source.dll
17:11:08.361:     frontend-tools.dll
17:11:08.361:     enc-amf.dll
17:11:08.361:     decklink-ouput-ui.dll
17:11:08.361:     decklink-captions.dll
17:11:08.361:     coreaudio-encoder.dll
17:11:08.361: ---------------------------------
17:11:08.362: ==== Startup complete ===============================================
17:11:08.379: All scene data cleared

**Comment by Nemnon** [comment]
17:18:22.686: ---------------------------------
17:18:22.686: [DShow Device: 'Устройство захвата видео 2'] settings updated: 
17:18:22.686: 	video device: Logitech HD Webcam C525
17:18:22.686: 	video path: \\?\usb#vid_046d&pid_0826&mi_02#7&267ecb85&0&0002#{65e8773d-8f56-11d0-a3b9-00a0c9223196}\{bbefb6c7-2fc4-4139-bb8b-a58bba724083}
17:18:22.686: 	resolution: 1600x896
17:18:22.686: 	flip: 0
17:18:22.686: 	fps: 30.00 (interval: 333333)
17:18:22.686: 	format: I420

**Comment by kounoike** [comment]
sorry for reply.
@Nemnon please add `Detector` filter on left-top area. this plugin requires Detector and Renderer filter.

**Comment by kounoike** [comment]
no reply
