### ISSUE TITLE
Add possibility to use it on Browser source

### ISSUE THREAD

**Issue by snip** [kounoike/obs-virtualbg#51]
Is there a possibility to use this plugin on a browser source?
(I would like to use it with output of vdo.ninja)

Currently the detection seems not possible on browser source.

Thanks

**Comment by kounoike** [comment]
@snip It's not a plugin issue. please open an issue on obsproject/obs-studio.

**Comment by snip** [comment]
So no workaround exist?
Can something like https://vingester.app/ may works?

**Comment by kounoike** [comment]
@snip I have an idea! Which use two instance of OBS Studio.

OBS1: Browser Source -> VirtualCam output
OBS2: VirtualCam input -> virtualBG filter -> Live Streaming.

**Comment by snip** [comment]
I just tested and it does works correctly with https://vingester.app/ & NDI pluggin on which i can add the detection.
