### ISSUE TITLE
Installation Instructions for macOS

### ISSUE THREAD

**Issue by GrandWasTaken** [kounoike/obs-virtualbg#54]
# Can we have proper installation instructions for macOS. Currently there is only instructions for windows.

**Comment by norihiro** [comment]
This is an instruction for another plugin but steps should be similar.
https://github.com/norihiro/obs-color-monitor/wiki/Install-MacOS#gui-installation-from-zip-package
https://github.com/norihiro/obs-color-monitor/wiki/Install-MacOS#terminal-installation-from-zip-package

**Comment by kounoike** [comment]
Please use normal text. not headings
