### ISSUE TITLE
Apple Code Signing

### ISSUE THREAD

**Issue by kounoike** [kounoike/obs-virtualbg#70]
I developed obs-virtualbg plugin for Mac with CoreML support. But I cannot distribute it.
Because I am not a member of the Apple Developer Program and therefore cannot perform code signing.

Is there anyone who can help me?

plan 1: Support $99/yr for me
plan 2: join as a maintainer and provide certificates by your Apple Developer Program

**Comment by lifted-jk** [comment]
I have an Apple Dev account. I'd be interested in this.

**Comment by ecc521** [comment]
@kounoike 
I have a developer account as well. I'm assuming you have this worked out, but if not, just let me know.

**Comment by mukeshsolanki** [comment]
@kounoike is this sorted out i dont see a mac version yet? Do you still need help with this?

**Comment by jackklink** [comment]
Trying to get the Mac version to install, but it is not working. I've followed the instructions to a T, but the plugin does not show in the OBS app. Did something change in the OBS app regarding how plugins are installed?
