### ISSUE TITLE
Adding to filters causes input device to freeze.

### ISSUE THREAD

**Issue by gaa23** [kounoike/obs-virtualbg#75]
Adding the background filter effect causes my video capture device to freeze. It it peristent  even after removing the device entirely.

**Comment by kounoike** [comment]
Please add LOG

**Comment by tumblewood-dev** [comment]
Right before the crash. when initializing the plugin, it shows this in the log:

`12:10:28.587: [Virtual BG detector] Can't create Session error: Exception during initialization: D:\a\_work\1\s\onnxruntime\core\providers\dml\DmlExecutionProvider\src\FusedGraphKernel.cpp(64)\onnxruntime.dll!00007FFE58BA71AA: (caller: 00007FFE58BA661C) Exception(1) tid(5d40) 80004002 Interface wordt niet ondersteund
12:10:28.587: 
12:10:28.605: User added filter 'Virtual Background Detector' (virtualbg) to source 'Logitech'
12:10:28.633: [Virtual BG detector] frame size or format change detected
12:10:28.633: error:   Picture size 0x0 is invalid
12:10:28.633: video_scaler_create: av_image_alloc failed: -22
12:10:28.633: [Virtual BG detector] Can't create video_scaler_create -2`

**Comment by kounoike** [comment]
no logs provided (that one is other user). so, I'm closing this issue.
If you want to reopen or rise new issue, pleaase add entire log by attachement or code fence.
