### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by boberski666** [kounoike/obs-virtualbg#80]
When I add filter to my camera input all the video disapear. Only blank screen stays, empty one to be exact like it key out all.

**Comment by zwiglm** [comment]
> When I add filter to my camera input all the video disapear. Only blank screen stays, empty one to be exact like it key out all.

I second that.

**Comment by Predulus** [comment]
I third it.

@kounoike san , any idea when this will be fixed, please?

**Comment by baggyg** [comment]
When I add, OBS crashes

**Comment by Dugnom** [comment]
Not working, using all AMD and happy to give more information if there is any reaction by the maintainer. 

Thank you for your time.

**Comment by battosai30** [comment]
Same here : blank view when I add the filter

**Comment by mr-september** [comment]
Closed as completed? This is still a problem in Nov 2024.
