### ISSUE TITLE
Crashes with 28.0.1

### ISSUE THREAD

**Issue by matthewshaw53** [kounoike/obs-virtualbg#83]
Not working with 28.0.1 (new update, so to be expected), I've seen people having issues with earlier versions, and I'm wondering what version of OBS is currently working I need

**Comment by Karstenx1971** [comment]
confirmed instant crash OBS completely no error message  on Win 10 with latest OBS

**Comment by kounoike** [comment]
works correctly with OBS-Studio 28.0.1 / obs-virtualbg 1.1.0
