### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by magriggs** [kounoike/obs-virtualbg#90]
[Crash 2023-01-10 17-34-07.txt](https://github.com/kounoike/obs-virtualbg/files/10381145/Crash.2023-01-10.17-34-07.txt)

**Comment by magriggs** [comment]
Crashes as soon as I add audio/video filter.

**Comment by magriggs** [comment]
[2023-01-10 17-33-31.txt](https://github.com/kounoike/obs-virtualbg/files/10381138/2023-01-10.17-33-31.txt)

app log

**Comment by prochor666** [comment]
Crashed after Video background Detector was added.

[Crash 2023-01-17 12-52-09.txt](https://github.com/kounoike/obs-virtualbg/files/10434704/Crash.2023-01-17.12-52-09.txt)

**Comment by everyonecancode** [comment]
I had the same problem. Fixed by updating OBS to 29.0.2

**Comment by endian675** [comment]
This can be closed, it's fixed by OBS 29.0.2 as found by @everyonecancode

**Comment by devmaxime** [comment]
Same problem on fresh install of the lastest OBS version. 29.0.2. It doesn't work.
